defaults:
  - dataset: idrid # idrid # idrid # # # eyepacs # # #remember space
  - model: dense121 # dense121 #convnext # convnext  # convnext  # efficientnet # convnext # convnext # dense121 #basic_cnn #efficientB2 #
  #- train_module/optimizer: adamw
  - train_module/aug: upsample_fixed
  - train_module/aug_other: none
  - train_module/loss: five_focal_ce
  - train_module/metrics: five
  - _self_

name: default_5c

wandb:
  init:
    enable: true
    #entity: "zizi-Deep-Learning-Labor"
    project: NEW_DR_5class
    name: "${save.date_prefix}_${model.name}"
    group: DR_${model.name}_${problem.name}
    tags: 
      - DR
      - ${problem.name}
      - ${model.name}
    id: null

problem:
  name: fiveclass
  num_classes: 5

# Training
runner:
  _target_: runners.run_train_5c

epochs: 1
lr: 0.001
# Logging
log_interval: 10 # 100-EyePACS 2-IDRID
eval_interval: 1
patience: 20 # Early Stopping

train:
  metric: f1
  lambda_d:  #
  use_ord: true
  lambda_ord: 0.5


# Saving
save:
  base_dir: "./checkpoints"
  model_name: ${model.name}
  date_prefix: ${now:%Y%m%d_%H%M}
  save_dir: "${save.base_dir}/${save.model_name}"
  file_name: "${save.date_prefix}_5c_best_model_epoch${epochs}.pth" #important changed point
  path: "${save.save_dir}/${save.file_name}"

#save_path: ./checkpoints/ensemble/12_15_RUN2_attention_best_model_m1_u2_epoch20.pth
#./checkpoints/dense/12_10_2c_idrid_best_model_m1_u2_epoch10.pth



# Testing
# Check for test evaluation of passed model path
test:
  name: test_5c
  check_mode: false
  check_path: null
# ./checkpoints/dense/12_09_5c_idrid_best_model_m1_u1_epoch20.pth

